# Site settings
title: My Random Musings
email: gshakhn@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Random musings by George Shakhnazaryan
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://gshakhn.com" # the base hostname & protocol for your site
twitter_username: gshakhn
github_username:  gshakhn

# Build settings
markdown: kramdown
